### PR TITLE
feat: Add automatic nightly builds to the Github Actions workflow

### PR DESCRIPTION
**Pull request by uznog**
Named after and hopefully resolving #1382

Changes include:
- workflow running at a cron schedule (12:00 AM / 00:00 UTC)
- workflow scheduled by cron runs `nightly` job, generating a pre-release

Nightly build name is `yazi-nightly-<timestamp>`. Flow tested with dummy artifact created:
https://github.com/uznog/yazi/actions/runs/10215675482

And here's the resulting pre-release: https://github.com/uznog/yazi/releases/tag/yazi-nightly-20240802-1236

### CODE REVIEW

**Comment by uncenter** [comment]
If I'm reading this right, this creates a new nightly release every day? I think creating a single `nightly`-tagged rolling release might be better 🤔 , though I might not be understanding exactly what this is trying to solve.

**Comment by uznog** [comment]
I totally agree. I pushed a commit changing tag name to be a static `nightly`, which will work as the latest version built off master branch every day

**Comment by sxyazi** [comment]
Thanks for the PR! 

Could you also add a build time to it? Something like: 

```
From commit: d2ebadb
Generated on: 2024-08-04 23:00:00 UTC
```

**Comment by uznog** [comment]
I guess this does the job:
https://github.com/uznog/yazi/releases/tag/nightly

**Review by sxyazi — APPROVED** [review]
Thanks!

**Pull request merged**
