### PR TITLE
Add cond for `hidden_dir`

### PR DESCRIPTION
**Pull request by jamylak**
So now you can do the following example:

```toml
prepend_conds = [
    # Fallback
    { if = "hidden_dir", text = "👻" },
    { if = "dir", text = "🗂️" },
]
```

### CODE REVIEW

**Comment by sxyazi** [comment]
```
prepend_conds = [
    { if = "hidden & dir", text = "👻" },
    { if = "dir", text = "🗂️" },
]
```

not work for you?

**Comment by jamylak** [comment]
Oh sorry I only ended up trying `hidden && dir`, didn't know about that one and must have missed it in docs, my bad

**Comment by sxyazi** [comment]
Oh looks like the doc doesn't describe this feature. 

Would you like to add your example to the docs? (just click the "Edit this page" link at bottom), some extra explanations would be great too ;)

**Comment by jamylak** [comment]
> Oh looks like the doc doesn't describe this feature.
> 
> Would you like to add your example to the docs? (just click the "Edit this page" link at bottom), some extra explanations would be great too ;)

I have added a PR for that, feel free to adjust to your liking. Thanks for the tip on combining `conds`

**Pull request closed without merging**
