### PR TITLE
fix: adjust `offset` value after resizing window

### LINKED ISSUE #1458: The cursor disappears in the preview panel when resizing yazi.
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (4150f401 2024-08-09)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.1
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/tlss/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When the window size is reduced, the out-of-bounds cursor cannot be displayed in the preview pane.

Preview panel cursor shows in fullscreen.
屏幕截图_20240810_154511

Preview panel cursor disappears after resizing the window.
屏幕截图_20240810_154538

### Minimal reproducer

1. Open yazi in fullscreen.
2. Enter the directory with a bunch of files.
3. Go to the bottom of this directory.
4. Resize the yazi window.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by TobisLee**
Fixes #1458

### CODE REVIEW

**Comment by sxyazi** [comment]
Thanks for the PR!

Would it be possible to move that logic into the [`arrow` method](https://github.com/sxyazi/yazi/blob/99a3b3a043502a32877148515d6992e0fa121137/yazi-fs/src/folder.rs#L65)? So that the `arrow` method not only resets the cursor position but also resets the offset? Since other parts are already using `arrow(0)` to reset the cursor position like this

https://github.com/sxyazi/yazi/blob/99a3b3a043502a32877148515d6992e0fa121137/yazi-fs/src/folder.rs#L61

https://github.com/sxyazi/yazi/blob/99a3b3a043502a32877148515d6992e0fa121137/yazi-fs/src/folder.rs#L92

**Comment by TobisLee** [comment]
Sure. I will try this and see if it works fine.

**Comment by TobisLee** [comment]
I move the `adjust_offset` inside the `arrow` method, it works fine for me. Please try this out and see if it works for you.

**Review by sxyazi — CHANGES_REQUESTED** [review]
I can't run it - I get a panic:

```sh
Backtrace (most recent call first):
  File "rust:library/core/src/panicking.rs", line 181, in core::panicking::panic_const::panic_const_sub_overflow
  File "/Users/saucer/code/yazi/yazi-fs/src/folder.rs", line 114, in yazi_fs::folder::Folder::adjust_offset
    if self.cursor >= max_offset { self.cursor - limit + scrolloff } else { self.offset };
  File "/Users/saucer/code/yazi/yazi-fs/src/folder.rs", line 76, in yazi_fs::folder::Folder::arrow
    self.adjust_offset();
  File "/Users/saucer/code/yazi/yazi-fs/src/folder.rs", line 87, in yazi_fs::folder::Folder::hover
    self.arrow(new - self.cursor as isize)
  File "/Users/saucer/code/yazi/yazi-core/src/tab/tab.rs", line 116, in yazi_core::tab::tab::Tab::apply_files_attrs
    parent.hover(&self.current.cwd);
  File "/Users/saucer/code/yazi/yazi-core/src/manager/commands/refresh.rs", line 18, in yazi_core::manager::commands::refresh::<impl yazi_core::manager::manager::Manager>::refresh
    self.active_mut().apply_files_attrs();
  File "/Users/saucer/code/yazi/yazi-fm/src/executor.rs", line 53, in yazi::executor::Executor::manager
    return self.app.cx.manager.$name(cmd, $($args),*);
  File "/Users/saucer/code/yazi/yazi-fm/src/executor.rs", line 18, in yazi::executor::Executor::execute
    Layer::Manager => self.manager(cmd),
  File "/Users/saucer/code/yazi/yazi-fm/src/app/app.rs", line 68, in yazi::app::app::App::dispatch_call
    fn dispatch_call(&mut self, cmd: Cmd, layer: Layer) { Executor::new(self).execute(cmd, layer); }
  File "/Users/saucer/code/yazi/yazi-fm/src/app/app.rs", line 55, in yazi::app::app::App::dispatch
    Event::Call(cmd, layer) => self.dispatch_call(cmd, layer),
  File "/Users/saucer/code/yazi/yazi-fm/src/app/app.rs", line 31, in yazi::app::app::App::serve::{{closure}}
    app.dispatch(event)?;
  File "/Users/saucer/code/yazi/yazi-fm/src/main.rs", line 62, in yazi::main::{{closure}}
    app::App::serve().await
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/park.rs", line 281, in tokio::runtime::park::CachedParkThread::block_on::{{closure}}
    if let Ready(v) = crate::runtime::coop::budget(|| f.as_mut().poll(&mut cx)) {
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/coop.rs", line 107, in tokio::runtime::coop::with_budget
    f()
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/coop.rs", line 73, in tokio::runtime::coop::budget
    with_budget(Budget::initial(), f)
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/park.rs", line 281, in tokio::runtime::park::CachedParkThread::block_on
    if let Ready(v) = crate::runtime::coop::budget(|| f.as_mut().poll(&mut cx)) {
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/context/blocking.rs", line 66, in tokio::runtime::context::blocking::BlockingRegionGuard::block_on
    park.block_on(f)
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/multi_thread/mod.rs", line 87, in tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
    blocking.block_on(future).expect("failed to park thread")
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/context/runtime.rs", line 65, in tokio::runtime::context::runtime::enter_runtime
    return f(&mut guard.blocking);
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/scheduler/multi_thread/mod.rs", line 86, in tokio::runtime::scheduler::multi_thread::MultiThread::block_on
    crate::runtime::context::enter_runtime(handle, true, |blocking| {
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/runtime.rs", line 363, in tokio::runtime::runtime::Runtime::block_on_inner
    Scheduler::MultiThread(exec) => exec.block_on(&self.handle.inner, future),
  File "/Users/saucer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.3/src/runtime/runtime.rs", line 335, in tokio::runtime::runtime::Runtime::block_on
    self.block_on_inner(future)
  File "/Users/saucer/code/yazi/yazi-fm/src/main.rs", line 62, in yazi::main
    app::App::serve().await

The application panicked (crashed).
  attempt to subtract with overflow
in yazi-fs/src/folder.rs, line 114
thread: main
```

**Comment by TobisLee** [comment]
I update the code. Please try it and see if it works.

**Review by sxyazi — APPROVED** [review]
Thanks a lot!

**Pull request merged**
