### PR TITLE
fix: refresh after bulk renaming (#1418)

### LINKED ISSUE #1418: No re-sort after mass name change
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 32.3

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When I select several filenames and change them. I then save and return to yazi. Unfortunately, the display does not re-sort to reflect new file order. I need to leave the directory and enter again to get a re-sort.

### Minimal reproducer

Select several files and select "r" to change the names. Change the names in a way that would change the sort order. Save and return.

### Anything else?

I suggest forcing a re-sort after a mass name change. Or at least providing a command to refresh/reload a directory.

### PR DESCRIPTION
**Pull request by TobisLee**
Fixes #1418

### CODE REVIEW

**Comment by AnirudhG07** [comment]
can we have refresh, not just after bulk-renaming, but many more places? For example, after mactag, you have to quit and refresh for things to show up. Various issues pointing to exiting and coming back for effects to show up, should be solved if refresh can be placed somewhere more general in my opinion...

**Comment by TobisLee** [comment]
> should be solved if refresh can be placed somewhere more general in my opinion...

I agree with you, but I'm not sure if this will become a performance bottleneck since the `refresh()` function resorts files.

As for this PR, it actually fixes two issues:
1. The lack of re-sorting after bulk renaming.
2. When bulk renaming files in both the current directory and a subdirectory, the files from the subdirectory appear in the current directory after renaming.

Here is the video for the second issue.

[Kooha-2024-08-19-11-56-40.webm](https://github.com/user-attachments/assets/2b04e761-9daa-4a1d-864d-231a1aa94bef)

**Comment by AnirudhG07** [comment]
I was seeing some issues and i found #62, might be why it wasnt implemented so far. Also wondering why is it still open?

**Comment by TobisLee** [comment]
Yeah, seems like `refresh()` does reduce the performance. I'll close this pr.

**Pull request closed without merging**
