### PR TITLE
feat: prompt users without `fzf` for the `zoxide` plugin

### LINKED ISSUE #1851: Give users a prompt if they don't have fzf installed (fundamentally important for zoxide integration)
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7c445ce 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (7c445ce 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":1")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/home/lucca/.cargo/bin/nu")
    EDITOR             : Some("/home/lucca/user_installs/helix/target/release/hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: Some("diligent-lake")
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.44.1
    fd               : No such file or directory (os error 2)
    rg               : No such file or directory (os error 2)
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/lucca/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

zoxide usage will be broken inside yazi if the user does not have fzf installed

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Give users a prompt if they don't have fzf installed

This could be after running yazi for the first time or when the user tries to run zoxide for the first time

### Additional context

_No response_

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

### PR DESCRIPTION
**Pull request by hankertrix**
Also fixed some local variables that were redefined.

Closes #1851.

### CODE REVIEW

**Comment by sxyazi** [comment]
Zoxide already provides a clear error message when `fzf` is not found:

```
❯ zoxide query -i
zoxide: could not find fzf, is it installed?
```

I think we could just display that error message to the user when `zoxide query` fails, instead of checking for `fzf` existence beforehand. This way, we can avoid unnecessary `fzf` process creation overhead.

**Comment by hankertrix** [comment]
Ahhh I see, I'll update it to use that.

Sorry, I don't use zoxide.

**Comment by sxyazi** [comment]
No worries, you're doing great! 

Thanks for your PR, merging now

**Review by sxyazi — APPROVED** [review]
Thank you!

**Pull request merged**
