### PR TITLE
feat: support image preview in Windows Terminal

### PR DESCRIPTION
**Pull request by e82eric**
Hi!  The latest version of windows terminal supports Sixel (https://github.com/microsoft/terminal/releases/tag/v1.22.2362.0) https://github.com/microsoft/terminal/pull/17421.

I wanted to make an attempt at updating Yazi to add support.  This looked like it would work for both images and video.  This may cause a regression for older versions of windows terminal since it won't fallback to chafa.

terminal-sixel

### CODE REVIEW

**Comment by sxyazi** [comment]
Yazi already supports Sixel through the standard [DA1 request](https://vt100.net/docs/vt510-rm/DA1.html). This means that as long as MS Terminal correctly sends the response indicating Sixel support, Yazi can recognize it without needing any additional detection.

But the DA1 response in Windows Terminal Preview 1.22.2362.0 is [currently broken](https://github.com/sxyazi/yazi/issues/1570#issuecomment-2319625368), so I can accept this PR as a temporary workaround until they fix it.

**Comment by e82eric** [comment]
Ahh,  I was wondering about that exact part of the code,  it was taking 10s to load and I saw that it was waiting for that da1 and timing out.  I will try and pull down that windows terminal branch and give it a try.

**Review by sxyazi — APPROVED** [review]
Thanks!

**Comment by sxyazi** [comment]
Hi @e82eric, could you send me an mp4 version of the PR gif demo? If possible, it would be great if you could make the window a bit smaller. 

I want to use it as the demo video for the upcoming version 0.3.3 release - Yazi is probably the first terminal file manager to support image preview in MS Terminal, especially when the standard DA1 isn't available now hah😄

**Comment by e82eric** [comment]
yep,  working on the mp4 now.

Quick update on the MS fix,  I tried that branch without my changes,  and the first attempt still tried to use chafa, I commented out this if statement and it correctly detected Sixel https://github.com/sxyazi/yazi/blob/e940d81d2a0a100fee41c1a59af7e2a14b49077f/yazi-adapter/src/adapter.rs#L95.  Maybe when the MS fix is merged that can be updated to just check for Tmux?

By the way, your project is awesome!

**Comment by sxyazi** [comment]
That's weird, this statement will only be entered if the `ZELLIJ_SESSION_NAME` env variable is detected:

https://github.com/sxyazi/yazi/blob/e940d81d2a0a100fee41c1a59af7e2a14b49077f/yazi-adapter/src/adapter.rs#L94-L96

Are you running Yazi in Zellij?

**Comment by e82eric** [comment]
Not running it in Zellij,  will try to step through it to see what was happening.  I was thinking it removed Sixel from everything that wasn't Zellij.

How does this look?

https://github.com/user-attachments/assets/22900e7b-9193-409f-b6da-e0afba1afda1

**Comment by sxyazi** [comment]
Looks great, thanks a lot!

**Comment by e82eric** [comment]
Quick update.  it looks like it was just this line that needed to commented out.  I think it is removing everything that isn't iterm2.

https://github.com/sxyazi/yazi/blob/e940d81d2a0a100fee41c1a59af7e2a14b49077f/yazi-adapter/src/adapter.rs#L93

**Comment by sxyazi** [comment]
Ah that makes sense, this is to ensure compatibility with third-party terminals that rely on the older version of ConPTY (like WezTerm and Mintty) for displaying images, so it still needs to be kept for now, and as time goes on and with OS updates, we can remove it in the future.

**Comment by e82eric** [comment]
That makes sense,  side note, start time was back to 0 on the branch with the MS fix.

**Comment by sxyazi** [comment]
Thanks for testing, I've edited the content of this PR and added some notes about it

**Pull request merged**
