### PR TITLE
fix: collect and fix all hard coded themes and color

### PR DESCRIPTION
**Pull request by Eric-Song-Nop**
- [x] Which
- [x] Tasks
- [x] A color in manager/folder (not sure what is that)
- [x] help
- [x] find arrow
- [x] header
- [x] input
- [x] select  

Plz let me know if there is more.
#149 #161

### CODE REVIEW

**Comment by sxyazi** [comment]
Excellent work!

**Comment by Eric-Song-Nop** [comment]
still need to fix ansi color problem

**Comment by Eric-Song-Nop** [comment]
Fix ansi

**Comment by sxyazi** [comment]
Sorry for taking so long to address this PR.

I will merge it once https://github.com/sxyazi/yazi/pull/161 is completed, since pr-161 breaks some things, such as removing the `.get()` method from `THEME.xxx.get()`. It shouldn't be too far off. 🚀

**Pull request merged**
