### PR TITLE
feat: sort naturally

### PR DESCRIPTION
**Pull request by asim215**
I start to prepare for implementation of natural sorting. But after adding new way of sorting, I expect menu changed and natural sorting appear, but it don't. Where I need to look for that?
For now sorting natural mush act as alphabetical, I will change it later.
Changes in formating created by rust auto format.

### CODE REVIEW

**Comment by sxyazi** [comment]
Thanks for the PR!

> I expect menu changed and natural sorting appear, but it don't

Does it mean the whichkey menu?

**Comment by asim215** [comment]
> Does it mean the whichkey menu?

Yes. I thought it reads keymap.toml and forms whichkey menu from that. Where do I need to look to fix that? I am not really good at Rust right now, but learning. :)
image

**Comment by sxyazi** [comment]
I'll look into it later.

**Comment by asim215** [comment]
Merge sorting keymap here.
I need advice. I don't have enough knowledge in Rust to decide correct way. 
I create 2 functions: cmp_natural, cmp_natural_file. And also doubt about how to upwrap file_name correctly to compare.
Which menu is not detecting natural sorting. But I was able to turn it on in config yazi.toml, both natural and natural --reverse.

<details>
  <summary>Natural sort screenshot</summary>

  image

</details>
<details>
  <summary>Natural --reverse sort screenshot</summary>

  image

</details>

**Pull request merged**
