### PR TITLE
feat: new option to suppress 0.4 deprecation warnings

### PR DESCRIPTION
**Pull request by sxyazi**
An implementation of the feature request: https://github.com/sxyazi/yazi/issues/2026

Closes https://github.com/sxyazi/yazi/issues/2026

```toml
# yazi.toml
[manager]
_v4_suppress_deprecation_warnings = true
```

### CODE REVIEW

**Comment by uncenter** [comment]
Why is this version specific? Wouldn't it make sense to have it as a permanent field?

**Comment by sxyazi** [comment]
You mean using `suppress_deprecation_warnings` instead of `_v4_suppress_deprecation_warnings`?

The issue with this is that if a user enabled it in v0.4 and forgot to remove it, since it's not version-specific, they won't even see the deprecation warnings for the v0.5 API when they upgrade to v0.5. 

As a result, they might run into issues when the v0.5 API compatibility layer is completely removed, without realizing it.

**Comment by uncenter** [comment]
This seems like a hack though. Maybe "suppress_deprecation_warnings" has a value like `"0.4"` where it targets warnings in that range? Just something more dynamic. I'd hate to see this be removed and then requested again and brought back for _v5_... etc.

**Comment by sxyazi** [comment]
My plan is to remove this option when removing the 0.4 compatibility layer, since it feels weird to still have a `suppress_deprecation_warnings` if all the compatibility code (warnings) is gone as there's nothing left to "suppress". 

If we're going to make it permanent, we'd need to reconsider its name and position, placing it under `[manager]` feels odd.

Like the `[headsup]` and `disable_exec_warn` option [introduced in 0.3](https://github.com/sxyazi/yazi/pull/1045/files#diff-5ab1e81c585ce8f7ecd1931c48a9374a1b14e74748989d986c0c030e13358110), which were eventually removed along with the compatibility code though.

Overall, I think making it permanent is a bit of an overkill, especially since it's just a temporary workaround for the transition.

**Comment by uncenter** [comment]
Speaking as the person who edits the schemas adding all these temporary config options is not a good solution 😅 
Maybe add an option in the TUI itself that toggles an internal state property, so outside of the config? It can be like this, for a specific version, and cleared by Yazi by later versions.

**Pull request merged**
