### PR TITLE
fix: add `--follow` option to `paste` command

### PR DESCRIPTION
**Pull request by eatradish**
Instead of copying the file pointed to by the symlink , create a soft link to the original path under the pasted path

See #433

### CODE REVIEW

**Comment by sxyazi** [comment]
BTW another factor worth considering is that copying symlinks is more dangerous than copying actual files, as it can lead to the loss of user data, unless the user is truly aware of what they are doing and remains cautious.

**Comment by sxyazi** [comment]
@einhander Okay thank you for showing me its real use case. I will try to retain both modes in the next few days.

**Comment by eatradish** [comment]
> @eatradish I've just realized that `cp` behaves differently in macOS and Linux, and I did indeed reference macOS in my design since it's my development environment.
> 
> I did some tests on my Linux VM, where `/a/x` is a symbolic link. When I copied `/a` to `/b/c`:
> 
>     * If `x` points to an absolute path of a file, there's no issue; `/b/c/x --> /absolute/real-x`.
> 
>     * However, if it points to a relative path, it becomes a broken link; `/b/c/x --> ../real-x`, where `/b/real-x` doesn't exist.
> 
> 
> I'm curious if copying symlinks is truly necessary and if there are any practical use cases for it. I haven't actually used it in real scenarios, so let me know your thoughts.

I think the behavior of `cp` (GNU Coreutils) is to keep the behavior uniform with normal file copying in commland-line only (tty) environments, whereas under Windows when you copy a `shortcut' its target is also a shortcut, which is probably more common-sensical under a GUI

**Comment by sxyazi** [comment]
@eatradish Does this mean Yazi should keep the same default behavior as GNU Coreutils? i.e. to only copy the symlink itself rather than the actual file it points to?

**Comment by einhander** [comment]
> @eatradish Does this mean Yazi should keep the same default behavior as GNU Coreutils? i.e. to only copy the symlink itself rather than the actual file it points to?

@sxyazi  My opinion - Yes, Yazi should keep the same default behavior as GNU Coreutils.

**Comment by sxyazi** [comment]
Okay, I'll finish the remaining work on this PR.

**Comment by sxyazi** [comment]
Hey @eatradish, I've added a new `paste --follow` option and changed the default behavior to *not* follow. Please give it a try to see if it works for you!

**Pull request merged**
