### PR TITLE
feat: loop through to find

### PR DESCRIPTION
**Pull request by ndtoan96**
https://github.com/sxyazi/yazi/assets/33489972/7e143c33-f745-43fb-a70b-edee40d9d386

### CODE REVIEW

**Comment by ndtoan96** [comment]
They keymap for this one is weird. My hand keeps pressing `n` and `N` out of reflex.

**Comment by sxyazi** [comment]
Discussed with @magnetophon at Discord last time, changing the finding key to `n/N` to keep with Vim's conventions.

https://discord.com/channels/1136203602898194542/1136203604076802092/1156661656638734396

**Comment by sxyazi** [comment]
I made some simplifications and removed the previous tedious and lengthy iterators.

BTW, I just found out about `is_some_and` today, it can help me simplify a lot of `map_or(false, ...)`, really like it!

**Comment by magnetophon** [comment]
> Discussed with @magnetophon at Discord last time, changing the finding key to `n/N` to keep with Vim's conventions.
> 
> https://discord.com/channels/1136203602898194542/1136203604076802092/1156661656638734396

When I run the main branch, on commit e7eb459787c4501b6ffd5fec4a572e2ca2b75fca, next/previous is still bound to ``-``/``=``, instead of '``n``/``N``.
I renamed ``~/.config/yazi/``, so afaik I'm running the defualt config.

The wrapping is a nice feature and works great, thanks!

**Comment by sxyazi** [comment]
Hey @magnetophon, this PR doesn't include the key changes. Sorry for the misunderstanding, and I will create a new PR to complete it.

**Pull request merged**
