### PR TITLE
feat: add preset command to the `shell`

### PR DESCRIPTION
**Pull request by fzdwx**
previous issues #37 

support style:

```
{ on = [ "l", "g" ], exec = "shell --block lazygit" },


{ on = [ "l", "g" ], exec = "shell --block 'lazygit -foo bar'" },
```

### CODE REVIEW

**Comment by sxyazi** [comment]
I think it would be better to always show the input so that the user can finish the final editing of the template code.

When the user does not need to edit, explicitly pass the `--confirm`, i.e. `shell "echo 123" --confirm`

**Comment by fzdwx** [comment]
> I think it would be better to always show the input so that the user can finish the final editing of the template code.
> 
> When the user does not need to edit, explicitly pass the `--confirm`, i.e. `shell "echo 123" --confirm`

Good idea.

**Comment by fzdwx** [comment]
cc @sxyazi

**Comment by sxyazi** [comment]
Thanks, merged!

**Pull request merged**
