### PR TITLE
feat: add Winget publishes to CI/CD

### PR DESCRIPTION
**Pull request by MoaidHathot**
Now that `Microsoft/winget-pkgs` has `Yazi`'s initial manifest, we can use CI/CD to automatically publish new versions to Winget.

It is a bit hard to test, we will have to wait for the next Yazi release.

### CODE REVIEW

**Comment by sxyazi** [comment]
Thanks for the PR!

Is it possible to have `winget-releaser` triggered after the release is published? The current workflow creates a release draft after the build, but it doesn't actually publish it:

https://github.com/sxyazi/yazi/blob/ed6ae000d646f94d32f6a14aff246bd6c479a9b0/.github/workflows/release.yml#L143

and it's manually published after editing the release notes.

**Comment by MoaidHathot** [comment]
@sxyazi, we have a few options, which one do you prefer?
1. Add a "release" trigger to `release.yml` and use `if` conditions to determine what runs on `release` and whats on `push`. Something like:
    ```yml
    on:
      push:
        tags:
          - "v[0-9]+.[0-9]+.[0-9]+"
      release:
        types: [published]


        ...
        jobs:
          build-unix:
            if: github.event_name == 'push'
            ....
          build-windows:
            if: github.event_name == 'push'
            ...
          build-musl:
            if: github.event_name == 'push'
            ...
          build-snap:
            if: github.event_name == 'push'
            ...
         release:
            if: github.event_name == 'push'
            runs-on: ubuntu-latest
            ...
         winget:
            if: github.event_name == 'release' && github.event.action == 'published'
            runs-on: ubuntu-latest
            ...
    ```

2. Rename `release.yml` to `release-draft.yml` and create a new `release.yml` file that is triggered on `release` and `published` events and that will contain the `winget` step?
```yml
name: Release

on:
  release:
    types: [published]

jobs:
  winget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge: true
      - name: Winget
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: sxyazi.yazi
          installers-regex: 'yazi-(x86_64|aarch64)-pc-windows-msvc\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
```

I'm in favor of option 2 as it is cleaner and easier to maintain since we don't need to maintain "if" conditions. In addition, it will be easier to add more publication targets in the future.

**Comment by sxyazi** [comment]
I love the second option too, it looks great!

**Comment by MoaidHathot** [comment]
I have updated the files accordingly :)
Do you have an idea how we can test it "in production"? Are you planning a new release soon?

**Comment by sxyazi** [comment]
Thanks for the change!

> Are you planning a new release soon

Yeah I will release v0.3 soon.

**Review by sxyazi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
