### PR TITLE
feat: add support portrait orientation preview for EXIF image

### PR DESCRIPTION
**Pull request by TobisLee**
#1411 

Tested with `cr2`, `nef`, `arw` images

screenshot_20240804_222125

### CODE REVIEW

**Comment by sxyazi** [comment]
Thanks for the PR! 

Could you upload an image that needs orientation for testing?

**Comment by TobisLee** [comment]
Sure. Can I upload the image to the `assets` folder, or where should I upload it?

**Comment by TobisLee** [comment]
To keep the yazi project clean, I uploaded some sample images to my project. You can get them at: https://github.com/TobisLee/sample-portrait-images/blob/main/_Z302267.NEF

**Comment by TobisLee** [comment]
I can't upload the image in the comment. To keep the yazi project clean, I uploaded some sample images to my project. You can download them at: https://github.com/TobisLee/sample-portrait-images/blob/main/_Z302267.NEF

**Review by sxyazi — APPROVED** [review]
Thanks!

**Pull request merged**
