### PR TITLE
feat: add `is_absolute`, `has_root`, `starts_with`, `ends_with`, `strip_prefix` to `Url` Userdata

### PR DESCRIPTION
**Pull request by sxyazi**
Supersedes https://github.com/sxyazi/yazi/pull/1603

### CODE REVIEW

**Comment by AnirudhG07** [comment]
Any docs needed for this? If yes, pls mention it in yazi-rs, I'll add it later. Hope its fine!

**Comment by AnirudhG07** [comment]
sure. no problems. leave that to the community to do XD

**Comment by ionnux** [comment]
Can you also add is_dir too?

**Comment by AnirudhG07** [comment]
sxyazi will add a Tracker issue, which will contain what all to add. 
And we can surely add on `is_dir` as well.

**Pull request merged**
