### PR TITLE
chore(nix): update dependencies

### PR DESCRIPTION
**Pull request by XYenon**

### CODE REVIEW

**Review by sxyazi — APPROVED** [review]
Sweet, thanks alot!

**Comment by uncenter** [comment]
FYI in the future this should probably be a `refactor(nix)!: ...` due to it both being breaking for users and changing the structure of the code. `chore(nix):` would be for things like updating the flake inputs. Not that it matters much and I'm not sure how much @sxyazi cares, but it makes it more difficult to follow changes to the Nix code here.

**Comment by sxyazi** [comment]
Thanks for the heads-up @uncenter, I've updated the title.

Sorry my poor nix-fu put it in the wrong category

**Comment by uncenter** [comment]
Ahah no worries, thank you.

**Pull request merged**
