### PR TITLE
feat: better accessibility

### PR DESCRIPTION
**Pull request by sxyazi**
Also fixes https://github.com/sxyazi/yazi/issues/709 - @VeeBop

### CODE REVIEW

**Comment by Brixy** [comment]
Dear @sxyazi,

Thanks for this commit.

I just noticed that whenever a file with mime-type `text/*` is hovered, columns 1 and 2 disappear completely.

Tested with default configs and Rust 1.75.

**Comment by sxyazi** [comment]
Hi @Brixy, please paste your `~/.local/state/yazi/yazi.log` content here let me know what happened

**Comment by Brixy** [comment]
Thanks a lot for investigating. 

<details>
<summary>yazi.log</summary>

```
  [2m2024-02-24T13:45:45.922439Z[0m [31mERROR[0m [1;31myazi::lives::lives[0m[31m: [31mruntime error: [string "yazi-plugin/src/loader.rs:59:28"]:18: attempt to index a nil value (local 'style')
stack traceback:
	[C]: in metamethod 'index'
	[string "yazi-plugin/src/loader.rs:59:28"]:18: in function 'folder.peek'[0m
    [2;3mat[0m yazi-fm/src/lives/lives.rs:66

  [2m2024-02-24T13:45:46.152679Z[0m [31mERROR[0m [1;31myazi::components::manager[0m[31m: [31mruntime error: [string "yazi-plugin/src/plugin.rs:25:13"]:17: attempt to index a nil value (local 'style')
stack traceback:
	[C]: in metamethod 'index'
	[string "yazi-plugin/src/plugin.rs:25:13"]:17: in method 'render'
	[string "yazi-plugin/src/plugin.rs:29:13"]:29: in function <[string "yazi-plugin/src/plugin.rs:29:13"]:18>[0m
    [2;3mat[0m yazi-fm/src/components/manager.rs:17

  [2m2024-02-24T13:45:46.176824Z[0m [31mERROR[0m [1;31myazi::components::manager[0m[31m: [31mruntime error: [string "yazi-plugin/src/plugin.rs:25:13"]:17: attempt to index a nil value (local 'style')
stack traceback:
	[C]: in metamethod 'index'
	[string "yazi-plugin/src/plugin.rs:25:13"]:17: in method 'render'
	[string "yazi-plugin/src/plugin.rs:29:13"]:29: in function <[string "yazi-plugin/src/plugin.rs:29:13"]:18>[0m
    [2;3mat[0m yazi-fm/src/components/manager.rs:17
```

</details>

**Comment by sxyazi** [comment]
So weird, I can't reproduce it, do you have any Yazi configurations? Could you zip them and upload?

**Comment by Brixy** [comment]
Thanks! I tested this commit without my own config files, falling back to default configuration files.

**Comment by sxyazi** [comment]
Hi @Brixy, I made a PR trying to fix this issue, let me know if it works for you, https://github.com/sxyazi/yazi/pull/721

**Comment by Brixy** [comment]
Brilliant. Works perfectly now. Thank you very much!

**Pull request merged**
