### PR TITLE
feat: add more supported archive formats to the preset config

### PR DESCRIPTION
**Pull request by Integral-Tech**
References:
- https://documentation.help/7-Zip-18.0/formats.htm
- https://www.digipres.org/formats/mime-types
- https://mimetype.io
- https://github.com/file/file

### CODE REVIEW

**Comment by Integral-Tech** [comment]
@sxyazi This PR has been completed :) Would you like to review it?

**Comment by sxyazi** [comment]
Thanks for the PR!

I noticed you referenced the supported formats of `7zip`, but `7zip` has several different versions. On Arch Linux, [Yazi uses `p7zip`](https://yazi-rs.github.io/docs/installation#arch-linux), which is a fork of `7zip`, while on macOS, it [uses `7zip`](https://yazi-rs.github.io/docs/installation#homebrew) (`sevenzip`), I'm not sure about Windows. 

The supported formats often vary between them. For default configuration, we need to consider the formats supported across all platforms, which means focusing on the smallest common subset - supported by both `7zip` and `p7zip` on Linux, macOS and Windows. 

This PR includes many formats I've never seen before, which makes testing them much more difficult. I think we can limit it to common formats that have been verified to work. This would also simplify the rules, especially considering that `7zip` is just a temporary solution during the transition. Eventually, I'll implement it myself (see https://github.com/sxyazi/yazi/issues/1864#issuecomment-2447902303), but it's unlikely to support all the formats `7zip` does, which would also help reduce confusion once we switch to another tool.

**Comment by Integral-Tech** [comment]
@sxyazi I just removed `application/zlib` which is not supported by `p7zip`. 

Additionally, `.dmg` & `.DMG` is added as not all `.dmg` files have MIME type `application/apple-diskimage`. Take case of [Icalingua++](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases/download/v2.12.24/Icalingua++-2.12.24.AppImage), it has `application/zlib` MIME type.

**Review by sxyazi — APPROVED** [review]
LGTM, thank you so much!

**Pull request merged**
