### PR TITLE
feat: find

### PR DESCRIPTION
**Pull request by sxyazi**
An implementation of the feature request: https://github.com/sxyazi/yazi/issues/81

Close https://github.com/sxyazi/yazi/issues/81

---

https://github.com/sxyazi/yazi/assets/17523360/425aa023-cdb0-4d77-991d-c68472a5a7f4

### CODE REVIEW

**Comment by teto** [comment]
what software do you use to capture the video ? I like that but what would be even better is to update the selected item on each keypress way rather than waiting for the Enter keypress (similar to how ranger does)

**Comment by sxyazi** [comment]
> what software do you use to capture the video

https://github.com/wulkano/Kap

> I like that but what would be even better is to update the selected item

Do you mean the "filter" feature of ranger? It seems a duplicate of the existing "search".

**Comment by teto** [comment]
for people passing by, I answered here https://github.com/sxyazi/yazi/issues/81#issuecomment-1707372346

**Comment by sxyazi** [comment]
Hey @teto, I believe I have implemented it in the way of Ranger, please give it a try.

The video has been updated to demonstrate it.

**Comment by teto** [comment]
Thanks I've just tested and that's exactly what I wanted <3 and I think it'sobjectively better than the initial behavior .

NB: Unrelated question but how could I map C-w to erase the last word. I tried doing so while testing the feature but  was not sure how.

**Comment by sxyazi** [comment]
> NB: Unrelated question but how could I map C-w to erase the last word. I tried doing so while testing the feature but was not sure how.

`C-w` and these keybindings are included in the "Emacs readline keybindings for the Input component" feature, which has been documented in the Feature requests. I will find some time to implement it.

**Comment by c02y** [comment]
Sorry, I cannot activate the four `find` commands (`find/find --previous/find_arrow/find_arrow --previous`) using the builtin shortcuts like `/`.

`yazi 0.1.4-1`
`Arch Linux`

**Comment by sxyazi** [comment]
@c02y This feature will be shipped with Yazi v0.1.5, you can build it from code to use it ahead

**Pull request merged**
