### PR TITLE
feat: new theme system

### LINKED ISSUE #204: A more visually explicit cut/yank mode
We can mark files to be yanked by using `yank` or `yank --cut`, but it's impossible to tell visually which file has been marked. An explicit visual marker for yanked/cut files like in `select` or `visual_mode` would be useful.

### LINKED ISSUE #246: remove operation don't complete
## Summary
According to the upstream issue https://github.com/Byron/trash-rs/issues/57

In my case, removing file(s) from the top-level of `$HOME` to trash will get the schedule progress bar not moving on, and the operation not be successful as well. Caused by `$HOME` and trash bin not being in the same device.

This scenario is common in users who use `tmpfs` as root or bind mount their `~/.local` to other devices.

```
# ~/.local/state/yazi/yazi.log

  2023-10-04T20:46:40.372878Z  INFO core::tasks::scheduler: Failed to work on task Trash(FileOpTrash { id: 5, target: "/home/elen/b", length: 0 }): Error during a `trash` operation: FileSystem { path: "/home/elen/.local/share/Trash/files/b.3", kind: CrossesDevices }
    at core/src/tasks/scheduler.rs:79
```

https://github.com/sxyazi/yazi/blob/4527044547af74802450efc4dad85dc0be2b40b7/core/src/tasks/workers/file.rs#L181-L183
This will block the progress bar.

System: Linux 6.5.5

### PR DESCRIPTION
**Pull request by sxyazi**
## TODOs:

Features:

- [x] Progress
- [x] Highlighting
- [x] Short path

Issues:

- [ ] https://github.com/sxyazi/yazi/issues/220
- [ ] https://github.com/sxyazi/yazi/pull/221, https://github.com/sxyazi/yazi/issues/149
- [x] https://github.com/sxyazi/yazi/issues/110#issuecomment-1728665761
- [x] Closes #204
- [x] Closes #246

The PR is bigger than anticipated and has taken more time.

There are still some unfinished works, additional PRs will be implemented shortly to prevent this one from continuing to expand.

### CODE REVIEW

**Comment by Brixy** [comment]
Thanks a lot for this excellent file manager! I use it on a daily basis.

I have played a bit with the current theming options and would like to suggest options to style

- executable files,
- symbolic links, and
- empty files (or maybe different colors for different file sizes, including 0 byte).

Maybe this can be (or already is?) considered in your new theme system. Thank you very much!

**Comment by sxyazi** [comment]
Thanks for the suggestions; this is something I've been planning to do all along, but it might not be included in this big PR but rather in the smaller one that follows, as part of a progressive enhancement.

**Comment by Brixy** [comment]
Excellent. Not only is your file manager of top quality, but also very well maintained! Thanks a lot for this.

**Comment by magnetophon** [comment]
> Excellent. Not only is your file manager of top quality, but also very well maintained! Thanks a lot for this.

I just wanted to repeat this! ❤

**Comment by magnetophon** [comment]
Not sure it it's ready for testing, but I just tried this branch, and got a crash:

```
  store                   │  0a9kdk3ialqxd8ckcb4764p2x3bzpdl1-jq-1.6-man             │  share thread 'main' panicked at 'cannot create a Lua reference, out of auxiliary stack space (used 1000197 slots)', /build/cargo-vendor-dir/mlua-0.9.1/src/lua.rs:3557:133bd7x0bs-kauth-5.110.0-dev      │
                            │  0bfh848j3il4zkdf7an9lqiinote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                            │  0bh9girfsnxryz6s9snmrl2pka4vs40h-nghttp2-1.51.0         │                                            fish: Job 1, 'nix run' terminated by signal SIGABRT (Abort)
                            │  0bw18xfl5x1f3w6v1b65zwarvcm7c7y7-hdf5-1.14.2            │                                                                                                       ⏎            
    ~/source/yazi   pr-9712724b !1 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✘ ABRT   39m 39s   1.69.0-nightly  18:28:04
❮ jhhh
                            │  0cc31xc2rdafrb45bf7895hb8y75xan6-alsa-lib-1.2.9-dev     │
  ```
  
I was browsing my nix store, which is huge.
I just copied the output as it appeared on my terminal, some of this is fro my prompt, some of it from the yazi gui, some of it from the error.

**Comment by sxyazi** [comment]
Hey @magnetophon, I've pushed a new optimized version, and it should work. Thanks for your interest in this ongoing feature.

**Comment by magnetophon** [comment]
> Hey @magnetophon, I've pushed [a new optimized version](https://github.com/sxyazi/yazi/commit/77e10053ca1643d221fce4c5731db6fad4a29c6a), and it should work. Thanks for your interest in this ongoing feature.

Now it's blazing fast again, with no crashes.
Thank you!

**Comment by sxyazi** [comment]
> I have played a bit with the current theming options and would like to suggest options to style

@Brixy Hi, this PR is completed. I have some time to work on it next. Would you like to file an issue for that?

**Pull request merged**
