### PR TITLE
feat: `open` support enter dir

### PR DESCRIPTION
**Pull request by fzdwx**

### CODE REVIEW

**Comment by sxyazi** [comment]
Thanks for the PR!

The behavior of enter not being able to open the file, but just enter to the directory is the expected behavior. Since the ability to enter an archive as a directory will be added later, and the files inside can be manipulated directly -- it's a file, but enterable!

You seem to be looking for a command with both `open` and `enter` functionality, and I think adding `enter` to `open` seems like a good option -- enter the selected file when it's a directory, not open.

**Comment by fzdwx** [comment]
你的意思我添加的这个功能会和一个未完成的功能的行为有冲突 ( 将压缩文件作为一个目录，然后 `enter` )

所以我应该把这个功能添加到 `open` 中， 让 `open` 具有 `enter` 的功能 ？

**Comment by sxyazi** [comment]
是的，如果 make sense 我会加上它。

---
Yes, if make sense I will add it.

**Comment by fzdwx** [comment]
@sxyazi cc

**Comment by sxyazi** [comment]
先合并，我再来改进下。默认 `<Right>` 映射改为 `open` 会丢失进入 archive 的功能，如果您不需要它可以在您的配置文件中覆盖它为 `open`。

---
Merge it first and I'll improve it. Changing the default `<Right>` mapping to `open` will lose the functionality of archive, if you don't need it you can override it in your config file.

**Comment by fzdwx** [comment]
这么说确实有点冲突

**Comment by sxyazi** [comment]
We've supported it now, see this tip https://yazi-rs.github.io/docs/tips/#smart-enter-enter-for-directory-open-for-file.

Note that Yazi main branch is currently required.

**Comment by fzdwx** [comment]
> We've supported it now, see this tip [yazi-rs.github.io/docs/tips/#smart-enter-enter-for-directory-open-for-file](https://yazi-rs.github.io/docs/tips/#smart-enter-enter-for-directory-open-for-file).
> 
> Note that Yazi main branch is currently required.

It's pretty cool ! Plugin system. ❤️

**Pull request merged**
